Basic Array Creation

In [ ]:
l=[1,2,3,4,5]
print("This is list : ",l)
import numpy as np
a=np.array(l)
print("This is array : ",a)

list does not support 2d
array does...

In [20]:
l=[[1,2,3],[4,5,6],[7,8,9]]
print(l)
a=np.array(l)
print(a)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [22]:
l=[["*","*"],["*","*"]]
print(l)

[['*', '*'], ['*', '*']]


In [24]:
a=np.array(l)
print(a)

[['*' '*']
 ['*' '*']]
