Joining of arrays

In [12]:
import numpy as np
a1=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
a2=np.array([[[10,11,12],[13,14,15],[16,17,18]]])
a3=np.concatenate((a1, a2), axis=0)
print(a3)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]


In [13]:
import numpy as np
a1=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
a2=np.array([[[10,11,12],[13,14,15],[16,17,18]]])
a3=np.concatenate((a1, a2), axis=1)
print(a3)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]
  [13 14 15]
  [16 17 18]]]


In [14]:
import numpy as np
a1=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
a2=np.array([[[10,11,12],[13,14,15],[16,17,18]]])
a3=np.concatenate((a1, a2), axis=2)
print(a3)

[[[ 1  2  3 10 11 12]
  [ 4  5  6 13 14 15]
  [ 7  8  9 16 17 18]]]
