Array Iteration

In [ ]:
# Iterating 1D array
import numpy as np
a1=np.array([1,2,3,4,5])
for a in a1:
    print(a)

1
2
3
4
5


In [ ]:
# iterating 2D array
a2=np.array([[1,2,3],[4,5,6]])
for b in a2:
    print(b)


2
[1 2 3]
[4 5 6]


In [5]:
# iterating 3D array
a3=np.array([[[1,2,3],[4,5,6]]])
print(a3.ndim)
for c in a3:
    print(c)

3
[[1 2 3]
 [4 5 6]]


Iteration through "N" dimensions

In [7]:
an=np.array([[1,2,3,4,5],[6,7,8,9,10]],ndmin=5)
for d in an:
    print(d)

[[[[ 1  2  3  4  5]
   [ 6  7  8  9 10]]]]


To return the actual values, the scalars, we have to iterate the arrays in each dimension.
Iterate on each scalar element of the 2-D array:

In [11]:
a=np.array([[[1,2,3],[4,5,6]]])
# We don't need the rows we need actual elements such as 1 2 3 ...
for x in a:
    for y in x:
        for z in y:
            print(z)

1
2
3
4
5
6


4D array --> output--> Actual elements (scalars)

In [14]:
a4d=np.array([[1,2,3,4,5],[6,7,8,9,10]],ndmin=4)
for a in a4d:
    for b in a:
        for c in b:
            for d in c:
                print(d)

1
2
3
4
5
6
7
8
9
10


In [15]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
  print(x)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


nditer function

In [16]:
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in np.nditer(arr):
  print(x)

1
2
3
4
5
6
7
8
