Joining of arrays

In [2]:
import numpy as np
a1=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
a2=np.array([[[10,11,12],[13,14,15],[16,17,18]]])
a3=np.concatenate((a1, a2), axis=0)
print(a1.shape)
print(a3)

(1, 3, 3)
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]


In [3]:
import numpy as np
a1=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
a2=np.array([[[10,11,12],[13,14,15],[16,17,18]]])
a3=np.concatenate((a1, a2), axis=1)
print(a3)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]
  [13 14 15]
  [16 17 18]]]


In [4]:
import numpy as np
a1=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
a2=np.array([[[10,11,12],[13,14,15],[16,17,18]]])
a3=np.concatenate((a1, a2), axis=2)
print(a3)

[[[ 1  2  3 10 11 12]
  [ 4  5  6 13 14 15]
  [ 7  8  9 16 17 18]]]


In [8]:
a=np.array([1,2,3])
b=np.array([4,5,6])
c=np.concatenate((a,b))
print(c)

[1 2 3 4 5 6]


In [9]:
import numpy as np

arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=1)

print(arr)


[[1 2 5 6]
 [3 4 7 8]]


In [10]:
import numpy as np

arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=0)

print(arr)


[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [11]:
x = np.array([[[1, 2]], [[3, 4]]])  
y = np.array([[[5, 6]], [[7, 8]]])
print(x.shape)

(2, 1, 2)


In [13]:
a = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

b = np.array([[[ 9, 10], [11, 12]],[[13, 14], [15, 16]]])

c=np.concatenate((a,b),axis=0)
print(c)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]

 [[13 14]
  [15 16]]]


In [14]:
a = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

b = np.array([[[ 9, 10], [11, 12]],[[13, 14], [15, 16]]])

c=np.concatenate((a,b),axis=1)
print(c)

[[[ 1  2]
  [ 3  4]
  [ 9 10]
  [11 12]]

 [[ 5  6]
  [ 7  8]
  [13 14]
  [15 16]]]


In [16]:
a = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

b = np.array([[[ 9, 10], [11, 12]],[[13, 14], [15, 16]]])

c=np.concatenate((a,b),axis=2)
print(c)

[[[ 1  2  9 10]
  [ 3  4 11 12]]

 [[ 5  6 13 14]
  [ 7  8 15 16]]]
