In [3]:
import numpy as np
print(np.__version__)


2.2.5


In [5]:
arr=np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [9]:
arr1=np.array((1,2,3,4,5,6,7,8))
print(arr1)

[1 2 3 4 5 6 7 8]


In [10]:
l1=[1,2,3]
print(l1)

[1, 2, 3]


In [15]:
a=np.array(10)
print(a)

10


In [22]:
a=np.array([[1,2,3],[4,5,6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [26]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [30]:
arr_2d=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr_2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [31]:
arr_3d=np.array([[[1,2,3],[4,5,6],[7,8,9],[10,11,12]]])
print(arr_3d)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]]


In [33]:
print(arr_2d.ndim)
print(arr_3d.ndim)

2
3


In [42]:


arr = np.array([1,2,3,4],ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5
