In [3]:
import numpy as np
# array 1-20
a=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20])
# print(arr)
# 5 by 4 matrix 
arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16],[17,18,19,20]])
print(arr)
# Extract 8
print("The desired element : ",arr[1,3])
# The entire 3rd row.
print("The 3rd row is : ",arr[2])
# The first two rows and first three columns.
print("The first two rows and first three columns",arr[0:2, 0:3])
# The last column of the matrix.
print("Last coloumn: ",arr[-1])
# All even numbers from the array.
print("Even numbers : ",a[1:20:2])
f=arr[0,0]




[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]
The desired element :  8
The 3rd row is :  [ 9 10 11 12]
The first two rows and first three columns [[1 2 3]
 [5 6 7]]
Last coloumn:  [17 18 19 20]
Even numbers :  [ 2  4  6  8 10 12 14 16 18 20]
