Checking the Datatype of array

In [4]:
import numpy as np
arr=np.array(([1,2,3,4,5],[6,7,8,9,10]))
print(arr)
print("The dimensions of array is : ",arr.ndim)
print(f"The data type of array {arr} is ",arr.dtype)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
The dimensions of array is :  2
The data type of array [[ 1  2  3  4  5]
 [ 6  7  8  9 10]] is  int64


In [5]:
arr=np.array(([1.1,2.2,3,4,5],[6,7,8.9,9.9,10]))
print(f"The data type of array {arr} is ",arr.dtype)

The data type of array [[ 1.1  2.2  3.   4.   5. ]
 [ 6.   7.   8.9  9.9 10. ]] is  float64


In [7]:
arr=np.array(([1.1,"2.2",3,4,"5"],[6,7,8.9,9.9,"10"]))
print(f"The data type of array {arr} is ",arr.dtype)

The data type of array [['1.1' '2.2' '3' '4' '5']
 ['6' '7' '8.9' '9.9' '10']] is  <U32


Creating arrays with defined datatype

In [22]:
a=np.array([1,2,3,4,5],dtype=object)
print(a)
print(a.dtype)
b=np.array([1,2,3,4,5],dtype=int)
print(b.dtype)
c=np.array([1,2,3,4,5],dtype=str)
print(c.dtype)
d=np.array([1,2,3,4,5],dtype=complex)
print(d.dtype)

[1 2 3 4 5]
object
int64
<U1
complex128
