Making copies of the arrays to convert the datatypes

In [8]:
import numpy as np
a=np.array([9.9,1,2])
b=a.astype('i')
print(a)
print(b)
print(a.dtype)
print(b.dtype)


[9.9 1.  2. ]
[9 1 2]
float64
int32


In [ ]:
c=np.array([1.1,1.3],dtype=int)
print(c.dtype)


int64


In [11]:
import numpy as np
a=np.array([0,2,3,0,5])
b=a.astype(bool)
print(a)
print(b)
print(a.dtype)
print(b.dtype)

[0 2 3 0 5]
[False  True  True False  True]
int64
bool


View and copy of array

In [24]:
# Orignal array (View)
arr = np.array([1, 2, 3, 4, 5])
# Copy
x = arr.copy()
# change in view
# arr[0] = 42

# print(arr)
print(x)

# change in copy
x[1]=9
print(x)
print(arr)



[1 2 3 4 5]
[1 9 3 4 5]
[1 2 3 4 5]


In [25]:
# base keyword
a1=np.array([1,2,3,4,5])
x=a1.copy()
y=a1.view()
print(x.base)
print(y.base)

None
[1 2 3 4 5]
