Array shape

In [7]:
import numpy as np
a=np.array([[1,2,3,4,5,9],[6,7,8,9,10,9]])
print(a.shape)
print(a)

(2, 6)
[[ 1  2  3  4  5  9]
 [ 6  7  8  9 10  9]]


In [9]:
a1=np.array([1,2,3,4])
print(a1.shape)

(4,)


In [11]:
a2=np.array([[1,2,3]])
print(a2.shape)

(1, 3)


Create an array with 5 dimensions using ndmin using a vector with values 1,2,3,4 and verify that last dimension has value 4:

In [2]:
import numpy as np
ar=np.array([1,2,3,4],ndmin=5)
print(ar.shape)

(1, 1, 1, 1, 4)


In [9]:
a4=np.array([1,2,3,4],ndmin=4)
print(a4)
print(a4.shape)

[[[[1 2 3 4]]]]
(1, 1, 1, 4)


In [ ]:
a4=np.array([[1,2,3,4],[5,6,7,8]],ndmin=4)
print(a4)
print(a4.shape)