Array Reshape

In [1]:
# converting from 1D TO 2D
import numpy as np 
a1=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
n1=a1.reshape(4,3)
print(a1)
print(n1)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [7]:
a1=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
n=a1.reshape(2,6)
print(n)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [13]:
# 1D to 3D
a3=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
n3=a3.reshape(2,3,2)
print(n3)


[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [12]:
# Elements change
import numpy as np
a3d=np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])
print("BEFORE RESHAPING: ")
print(a3d)
print("AFTER RESHAPING: ")
new3d=a3d.reshape(4,3)
print(new3d)

BEFORE RESHAPING: 
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
AFTER RESHAPING: 
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [13]:
a=np.array([1,2,3,4])
b=a.reshape(2,2)
print(b)
print(b.base)

[[1 2]
 [3 4]]
[1 2 3 4]
